from .base_class import Base
from ..API.v1.modules.employee.model import Employee
from ..API.v1.modules.employee_contact.model import EmployeeContact
from ..API.v1.modules.employee_relative.model import EmployeeRelative
from ..API.v1.modules.pension_situation.model import PensionSituation
from ..API.v1.modules.housing_situation.model import HousingSituation
from ..API.v1.modules.specialization.model import Specialization
from ..API.v1.modules.employee_job.model import EmployeeJob
from ..API.v1.modules.attachment.model import Attachment
