from .base_class import Base
from ..API.v1.modules.activity.model import Activity
from ..API.v1.modules.bank.model import Bank
from ..API.v1.modules.marital_status.model import MaritalStatus
from ..API.v1.modules.nationality.model import Nationality
from ..API.v1.modules.relationship.model import Relationship
from ..API.v1.modules.rsh.model import RSH
from ..API.v1.modules.scholarship.model import Scholarship
from ..API.v1.modules.type_home.model import TypeHome
from ..API.v1.modules.type_subsidy.model import TypeSubsidy
