version: "3"

services:
  employee-api:
    build: .
    restart: unless-stopped
    command: bash -c "alembic upgrade head && uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 80"
    volumes:
      - .:/app
    ports:
      - 5104:80
  db:
    restart: unless-stopped
    image: postgres:13-alpine
    volumes:
      - employees_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=Anakin
      - POSTGRES_PASSWORD=Anakin4
      - POSTGRES_DB=employees
volumes:
  employees_data:
