version: "3"

services:
  employee-api:
    build: .
    restart: unless-stopped
    command: bash -c "alembic upgrade head && uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 80"
    volumes:
      - .:/app
    ports:
      - 5104:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
