version: "3"

services:
  employee-api-test:
    image: cchcdev.azurecr.io/employee-service:latest
    domainname: employee-test
    container_name: employee-test
    command: bash -c "cd / && alembic upgrade head && uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 5194"
    ports:
      - 5194:5194