"""adding employee etnia

Revision ID: 149ea762e988
Revises: 2bf5e8a20457
Create Date: 2022-01-17 16:12:06.214677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149ea762e988'
down_revision = '2bf5e8a20457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('etnia', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'etnia')
    # ### end Alembic commands ###
