"""removing recognize and adding employee revision table

Revision ID: 172e9ee92000
Revises: 149ea762e988
Create Date: 2022-01-21 12:42:58.725806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172e9ee92000'
down_revision = '149ea762e988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_revision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assistance_id', sa.Integer(), nullable=False),
    sa.Column('assistance_names', sa.String(length=250), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('employee', 'recognize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('recognize', sa.VARCHAR(length=2), server_default=sa.text("'SI'::character varying"), autoincrement=False, nullable=False))
    op.drop_table('employee_revision')
    # ### end Alembic commands ###
