"""adding rsh status and making maternal surname non required at employee table

Revision ID: 174c3571fa0e
Revises: ac1febf7bc0d
Create Date: 2021-10-28 16:02:43.087732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174c3571fa0e'
down_revision = 'ac1febf7bc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('rsh_status', sa.String(length=10), nullable=True))
    op.alter_column('employee', 'maternal_surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'maternal_surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('employee', 'rsh_status')
    # ### end Alembic commands ###
