"""adding confirmation date

Revision ID: 1a6a4a94e8b6
Revises: 9aa500e83f99
Create Date: 2021-07-29 17:15:10.007885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a4a94e8b6'
down_revision = '9aa500e83f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_contact', sa.Column('confirmation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_contact', 'confirmation_date')
    # ### end Alembic commands ###
