"""adding assistance and social case status

Revision ID: 2b3da73b6d27
Revises: b89d64961abd
Create Date: 2022-02-08 16:52:00.946805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3da73b6d27'
down_revision = 'b89d64961abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('last_attention_date', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('hast_follow_attentions', sa.Boolean(), nullable=True))
    op.add_column('employee', sa.Column('has_social_case', sa.Boolean(), nullable=True))
    op.drop_constraint('employee_contact_employee_run_fkey', 'employee_contact', type_='foreignkey')
    op.create_foreign_key(None, 'employee_contact', 'employee', ['employee_run'], ['run'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_contact', type_='foreignkey')
    op.create_foreign_key('employee_contact_employee_run_fkey', 'employee_contact', 'employee', ['employee_run'], ['run'], ondelete='CASCADE')
    op.drop_column('employee', 'has_social_case')
    op.drop_column('employee', 'hast_follow_attentions')
    op.drop_column('employee', 'last_attention_date')
    # ### end Alembic commands ###
