"""adding isapre and fonasa name attr

Revision ID: 2bf5e8a20457
Revises: f1bf3e7f7967
Create Date: 2021-11-11 15:10:27.179179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf5e8a20457'
down_revision = 'f1bf3e7f7967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_situation', sa.Column('isapre_fonasa_name', sa.String(length=120), server_default='ISAPRE OFICIAL', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_situation', 'isapre_fonasa_name')
    # ### end Alembic commands ###
