"""delete unique constraint

Revision ID: 3950f361b5d7
Revises: 1a6a4a94e8b6
Create Date: 2021-07-29 20:33:33.155155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3950f361b5d7'
down_revision = '1a6a4a94e8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_contact_employee_run_key', 'employee_contact', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employee_contact_employee_run_key', 'employee_contact', ['employee_run'])
    # ### end Alembic commands ###
