"""creating tables

Revision ID: 49ade57325ae
Revises: 1338c1a9c819
Create Date: 2021-07-29 23:12:53.776321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ade57325ae'
down_revision = '1338c1a9c819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('property_home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('sub_specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('parent_specialty_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_specialty_id'], ['specialty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('housing_situation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type_home_id', sa.Integer(), nullable=False),
    sa.Column('property_home_id', sa.Integer(), nullable=False),
    sa.Column('type_subsidy_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=7), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['property_home_id'], ['property_home.id'], ),
    sa.ForeignKeyConstraint(['type_home_id'], ['types_home.id'], ),
    sa.ForeignKeyConstraint(['type_subsidy_id'], ['types_subsidy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pension_situation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('isapre_fonasa_id', sa.Integer(), nullable=False),
    sa.Column('afp_isp_id', sa.Integer(), nullable=False),
    sa.Column('is_pensioner', sa.String(length=2), nullable=False),
    sa.Column('pension_amount', sa.Float(), nullable=True),
    sa.Column('belongs_to_recognize', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=7), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['afp_isp_id'], ['afp_isp.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['isapre_fonasa_id'], ['isapre_fonasa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('specialty_detail_id', sa.Integer(), nullable=False),
    sa.Column('is_self_taught', sa.String(length=2), nullable=False),
    sa.Column('certifying_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_certificated', sa.String(length=2), nullable=True),
    sa.Column('certification_url', sa.String(length=255), nullable=True),
    sa.Column('certificated_date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=7), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certifying_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['specialty_detail_id'], ['sub_specialty.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization')
    op.drop_table('pension_situation')
    op.drop_table('housing_situation')
    op.drop_table('sub_specialty')
    op.drop_table('specialty')
    op.drop_table('property_home')
    op.drop_table('entity')
    # ### end Alembic commands ###
