"""adding names to employee job table

Revision ID: 71cc1d252a41
Revises: 893362924f49
Create Date: 2021-07-30 15:37:06.868661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cc1d252a41'
down_revision = '893362924f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_job', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('employee_job', sa.Column('construction_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_job', 'construction_name')
    op.drop_column('employee_job', 'business_name')
    # ### end Alembic commands ###
