"""creating employee job

Revision ID: 893362924f49
Revises: 49ade57325ae
Create Date: 2021-07-30 06:51:20.352504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893362924f49'
down_revision = '49ade57325ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('contract_term', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('leave_motive', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=7), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_job')
    # ### end Alembic commands ###
