"""Adding state to employee

Revision ID: 9280ba5ec9f6
Revises: 71cc1d252a41
Create Date: 2021-08-05 23:20:19.859279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9280ba5ec9f6'
down_revision = '71cc1d252a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('state', sa.String(length=7), server_default='CREATED', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'state')
    # ### end Alembic commands ###
