"""adding rsh status to employee relative

Revision ID: 9637a26fd0e7
Revises: 82fe4d85d07f
Create Date: 2021-11-05 15:51:16.480878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9637a26fd0e7'
down_revision = '82fe4d85d07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_relative', sa.Column('rsh_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_relative', 'rsh_status')
    # ### end Alembic commands ###
