"""adding specialization key

Revision ID: 98e83c144838
Revises: 1c4f6f67814e
Create Date: 2021-09-09 05:07:59.518592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e83c144838'
down_revision = '1c4f6f67814e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('file_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialization', 'file_key')
    # ### end Alembic commands ###
