"""removing attributes from relative table

Revision ID: 995ce972cca8
Revises: 5e65bcecb359
Create Date: 2021-09-09 04:17:41.693866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995ce972cca8'
down_revision = '5e65bcecb359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_relative', 'nationality')
    op.drop_column('employee_relative', 'relationship_name')
    op.drop_column('employee_relative', 'marital_status')
    op.drop_column('employee_relative', 'scholarship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_relative', sa.Column('scholarship', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employee_relative', sa.Column('marital_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employee_relative', sa.Column('relationship_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employee_relative', sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
