"""removing unique run rule  relative table

Revision ID: 9aa500e83f99
Revises: a391d94511d6
Create Date: 2021-07-28 22:56:15.745825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa500e83f99'
down_revision = 'a391d94511d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_relative_run_key', 'employee_relative', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employee_relative_run_key', 'employee_relative', ['run'])
    # ### end Alembic commands ###
