"""adding speciality and sub speciality to employee job table

Revision ID: aa9f0f2bf693
Revises: d3b63699aa96
Create Date: 2021-11-08 19:55:39.523367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9f0f2bf693'
down_revision = 'd3b63699aa96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_job', sa.Column('specialty_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('employee_job', sa.Column('specialty_name', sa.String(length=50), nullable=True))
    op.add_column('employee_job', sa.Column('specialty_detail_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('employee_job', sa.Column('specialty_detail_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_job', 'specialty_detail_name')
    op.drop_column('employee_job', 'specialty_detail_id')
    op.drop_column('employee_job', 'specialty_name')
    op.drop_column('employee_job', 'specialty_id')
    # ### end Alembic commands ###
