"""adding phone to employee relative table

Revision ID: ac1febf7bc0d
Revises: 29c769f03ec9
Create Date: 2021-10-28 15:47:56.390846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1febf7bc0d'
down_revision = '29c769f03ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_relative', sa.Column('phone', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_relative', 'phone')
    # ### end Alembic commands ###
