"""removing employee contact confirmation date

Revision ID: b89d64961abd
Revises: 172e9ee92000
Create Date: 2022-01-25 15:28:39.063886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b89d64961abd'
down_revision = '172e9ee92000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_contact', 'confirmation_date')
    op.create_unique_constraint(None, 'employee_revision', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_revision', type_='unique')
    op.add_column('employee_contact', sa.Column('confirmation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
