"""removing certication date as requerid from specialization table

Revision ID: c9d0ae1a5e25
Revises: 9280ba5ec9f6
Create Date: 2021-08-06 15:38:33.340867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9d0ae1a5e25'
down_revision = '9280ba5ec9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specialization', 'certificated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specialization', 'certificated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
