"""making not required employee relative maternal surname

Revision ID: d3b63699aa96
Revises: ce01dc4adda1
Create Date: 2021-11-08 15:30:33.881739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b63699aa96'
down_revision = 'ce01dc4adda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_relative', 'maternal_surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_relative', 'maternal_surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
