"""Creating employee table

Revision ID: e303a51a0e39
Revises: a1bd87b0f3f7
Create Date: 2021-07-28 21:19:03.330220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e303a51a0e39'
down_revision = 'a1bd87b0f3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run', sa.String(length=12), nullable=False),
    sa.Column('names', sa.String(length=120), nullable=False),
    sa.Column('paternal_surname', sa.String(length=120), nullable=False),
    sa.Column('maternal_surname', sa.String(length=120), nullable=False),
    sa.Column('born_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('marital_status_id', sa.Integer(), nullable=True),
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('disability', sa.String(length=2), nullable=False),
    sa.Column('credential_disability', sa.String(length=2), nullable=False),
    sa.Column('recognize', sa.String(length=2), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('alive', sa.String(length=2), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('rsh', sa.String(length=100), nullable=True),
    sa.Column('rsh_percentage', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['marital_status_id'], ['marital_status.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationality.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', 'run'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('run')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
