"""adding reconocer status to employee relative

Revision ID: f1bf3e7f7967
Revises: 31b4c673deee
Create Date: 2021-11-11 15:05:19.733844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bf3e7f7967'
down_revision = '31b4c673deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_relative', sa.Column('belongs_to_reconocer', sa.String(length=2), server_default='NO', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_relative', 'belongs_to_reconocer')
    # ### end Alembic commands ###
